	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 if (!TapeArray[518] ) {
	 head+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 if (!TapeArray[519] ) {
	 head+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 head+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 head+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 head+=1;
	 TapeArray[head]+=1;
	 head-=1;
	 head-=1;
	 head-=1;
	 head-=1;
	 TapeArray[head]-=1;
	 }
	 head+=1;
	 TapeArray[head]+=1;
	 head+=1;
	 TapeArray[head]+=1;
	 head+=1;
	 TapeArray[head]-=1;
	 head+=1;
	 head+=1;
	 TapeArray[head]+=1;
	 if (!TapeArray[524] ) {
	 head-=1;
	 }
	 head-=1;
	 TapeArray[head]-=1;
	 }
	 head+=1;
	 head+=1;
	 printf("(524)%c \n ",TapeArray[524]);
	 head+=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 printf("(525)%c \n ",TapeArray[525]);
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 head+=1;
	 head+=1;
	 printf("(527)%c \n ",TapeArray[527]);
	 head-=1;
	 TapeArray[head]-=1;
	 printf("(526)%c \n ",TapeArray[526]);
	 head-=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 TapeArray[head]-=1;
	 printf("(525)%c \n ",TapeArray[525]);
	 head+=1;
	 head+=1;
	 TapeArray[head]+=1;
	 printf("(527)%c \n ",TapeArray[527]);
	 head+=1;
	 TapeArray[head]+=1;
	 TapeArray[head]+=1;
	 printf("(528)%c \n ",TapeArray[528]);
 return 0; 
 }